import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { STRATEGIES } from '../fixers/strategy-engine.js';

export function generateMigrationGuide(scanResult, outputPath) {
  const { projectName, plan, peerConflicts, compatFindings, vulnerabilities } = scanResult;

  const sections = [
    `# Migration Guide: ${projectName}`,
    `> Generated by dep-doctor v2 — ${new Date().toISOString().split('T')[0]}`,
    '',
    '## Overview',
    '',
    `- Total issues: ${plan.length}`,
    `- Auto-fixable: ${plan.filter(p => p.effort === 'auto' || p.effort === '5min').length}`,
    `- Manual intervention: ${plan.filter(p => p.risk === 'high').length}`,
    '',
  ];

  // Phase 1: Safe upgrades
  const safeUpgrades = plan.filter(p => p.strategy === STRATEGIES.SAFE_UPGRADE && p.risk === 'low');
  if (safeUpgrades.length) {
    sections.push('## Phase 1: Safe Upgrades (auto-apply)');
    sections.push('```bash');
    for (const u of safeUpgrades) {
      sections.push(`npm install ${u.package}@${u.steps[0]?.target || 'latest'}`);
    }
    sections.push('npm test');
    sections.push('```');
    sections.push('');
  }

  // Phase 2: Overrides
  const overrides = plan.filter(p => p.strategy === STRATEGIES.OVERRIDE);
  if (overrides.length) {
    sections.push('## Phase 2: Override PeerDep Conflicts');
    sections.push('Add to package.json:');
    sections.push('```json');
    sections.push('"overrides": {');
    for (const o of overrides) {
      sections.push(`  "${o.package}": "..."  // ${o.reason}`);
    }
    sections.push('}');
    sections.push('```');
    sections.push('');
  }

  // Phase 3: Adapters
  const adapters = plan.filter(p => p.strategy === STRATEGIES.ADAPTER);
  if (adapters.length) {
    sections.push('## Phase 3: Adapter Pattern');
    for (const a of adapters) {
      sections.push(`### ${a.package}`);
      sections.push(`- Reason: ${a.reason}`);
      sections.push(`- Effort: ${a.effort}`);
      sections.push(`- Run: \`dep-doctor fix --strategy adapter --package ${a.package}\``);
      sections.push('');
    }
  }

  // Phase 4: Major upgrades with codemods
  const majors = plan.filter(p => p.strategy === STRATEGIES.MAJOR_UPGRADE);
  if (majors.length) {
    sections.push('## Phase 4: Major Upgrades (manual review required)');
    for (const m of majors) {
      sections.push(`### ${m.package}`);
      sections.push(`- ${m.reason}`);
      sections.push(`- Effort: ${m.effort}`);
      if (m.steps.some(s => s.action === 'codemod')) {
        sections.push('- Codemods will be applied automatically');
      }
      sections.push('');
    }
  }

  // Compat issues detail
  if (compatFindings?.length) {
    sections.push('## Code Changes Required');
    sections.push('');
    sections.push('| File | Line | Deprecated API | Replacement |');
    sections.push('|------|------|---------------|-------------|');
    for (const f of compatFindings.slice(0, 50)) {
      sections.push(`| ${f.file} | ${f.line} | ${f.api} | ${f.replacement} |`);
    }
    if (compatFindings.length > 50) {
      sections.push(`| ... | ... | ${compatFindings.length - 50} more | ... |`);
    }
    sections.push('');
  }

  const guide = sections.join('\n');
  writeFileSync(outputPath, guide);
  return { success: true, file: outputPath, lineCount: sections.length };
}
